### ISSUE TITLE
docs/02-Core-Concepts/03-Docker-vs-ContainerD.md 

### ISSUE THREAD

**Issue by nikunj436** [kodekloudhub/certified-kubernetes-administrator-course#144]
CONTAINER_RUNTIME_ENDPOINT needs to add more detail as 1 end point is depreciated as per 1.24 version. Some more detail about the sock

**Comment by fireflycons** [comment]
Please suggest how you might change it? The docker endpoint is valid and will be for the foreseeable  future as `crictl` can be used to get information about containers started by Docker, when using Docker alone rather than Kubernetes.

Please note also that this document is a transcript of the course lecture.

**Comment by fireflycons** [comment]
Closed /stale
