### ISSUE TITLE
Apple Silicon Docs Broken

### ISSUE THREAD

**Issue by quickchase** [kodekloudhub/certified-kubernetes-administrator-course#162]
The docs link to a script that does not exist:

https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/kubeadm-clusters/apple-silicon/docs/deploy-virtual-machines.sh

Linked via the following doc:
https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/kubeadm-clusters/apple-silicon/docs/02-compute-resources.md

> Because we cannot use VirtualBox and are instead using Multipass, [a script is provided](https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/kubeadm-clusters/apple-silicon/docs/deploy-virtual-machines.sh) to create the three VMs.

Should be updated to:
https://github.com/kodekloudhub/certified-kubernetes-administrator-course/blob/master/kubeadm-clusters/apple-silicon/deploy-virtual-machines.sh

**Comment by quickchase** [comment]
Also, the these docs don't mention the `IPALLOC_RANGE` ENV var during weave setup? It's referenced in the video series as a gotcha to watch out for.

**Comment by fireflycons** [comment]
Hi @quickchase 
The broken link has been fixed.

Regarding Weave, because we explicitly set the pod CIDR range to `10.244.0.0/16` this should not conflict with Weave when installed as it is with default settings. Should you have an error installing it, then please open a new issue here and include as much detail as possible including weave pod logs etc.
